FROM node:12
WORKDIR /home/node/app
COPY app /home/node/app
RUN npm install

ENV NEW_RELIC_NO_CONFIG_FILE=true
ENV NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true \
NEW_RELIC_LOG=stdout
ENV NEW_RELIC_LICENSE_KEY=02b3d79cebe1d2a0824d04f953098597FFFFNRAL
ENV NEW_RELIC_APP_NAME="node-docker"

CMD npm run app
EXPOSE 9999